version: "3.3"

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - FileCompress-net
  web:
    tty: true
    build:
      context: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - .:/FileCompressor
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - FileCompress-net
    depends_on:
      - postgres
volumes:
  pgdata:
networks:
  FileCompress-net: {}
